# This file was generated by GoReleaser. DO NOT EDIT.
cask "cognitive3d" do
  name "cognitive3d"
  desc "CLI tool for the Cognitive3D spatial analytics API"
  homepage "https://cognitive3d.com"
  version "0.5.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cognitive3d"

  on_macos do
    on_intel do
      url "https://github.com/CognitiveVR/cognitive3d-releases/releases/download/v#{version}/cognitive3d_#{version}_Darwin_x86_64.tar.gz"
      sha256 "0e9af0c39459a3af379ae011f30caf8ddc697602672dc16bc4d89967682e2507"
    end
    on_arm do
      url "https://github.com/CognitiveVR/cognitive3d-releases/releases/download/v#{version}/cognitive3d_#{version}_Darwin_arm64.tar.gz"
      sha256 "e38783aa295f406ad46331fcbab03b52d7a6c2f95469126c682ff3b2c1dda454"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/CognitiveVR/cognitive3d-releases/releases/download/v#{version}/cognitive3d_#{version}_Linux_x86_64.tar.gz"
      sha256 "33a8d3a2b321f022dbecc9ee3f48e7e79dacad1c4fa4af46c9ba61e9b85e4bf6"
    end
    on_arm do
      url "https://github.com/CognitiveVR/cognitive3d-releases/releases/download/v#{version}/cognitive3d_#{version}_Linux_arm64.tar.gz"
      sha256 "4f960ecc7fcb2ecfcb45584307dbd0253473e6f2a7c9e6a9d7c7fe3a9ede5ee4"
    end
  end

  # No zap stanza required
end
