# This file was generated by GoReleaser. DO NOT EDIT.
cask "cognitive3d" do
  version "0.10.3"

  on_macos do
    on_intel do
      url "https://github.com/CognitiveVR/cognitive3d-releases/releases/download/v#{version}/cognitive3d_#{version}_Darwin_x86_64.tar.gz"
      sha256 "ca07259d3a1644e2afae70c3e165939fe9ff9c3fef2ba13d2769de06880c6450"
    end
    on_arm do
      url "https://github.com/CognitiveVR/cognitive3d-releases/releases/download/v#{version}/cognitive3d_#{version}_Darwin_arm64.tar.gz"
      sha256 "a988cd1d0b9cb33b1aa060d39fd10554b271e84120c43c2b8a6fd9ae2ab268a3"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/CognitiveVR/cognitive3d-releases/releases/download/v#{version}/cognitive3d_#{version}_Linux_x86_64.tar.gz"
      sha256 "83ffe0d8063349205b58acd22e4bcff1131a7ccb361ebd9a09f753bf6e44e167"
    end
    on_arm do
      url "https://github.com/CognitiveVR/cognitive3d-releases/releases/download/v#{version}/cognitive3d_#{version}_Linux_arm64.tar.gz"
      sha256 "95f343dbe23ee0622c069d13fa0c55d1c95a26b00a9a5b7a04ea63c5a8251208"
    end
  end

  name "cognitive3d"
  desc "CLI tool for the Cognitive3D spatial analytics API"
  homepage "https://cognitive3d.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cognitive3d"

  # No zap stanza required

end
