# This file was generated by GoReleaser. DO NOT EDIT.
cask "cognitive3d" do
  name "cognitive3d"
  desc "CLI tool for the Cognitive3D spatial analytics API"
  homepage "https://cognitive3d.com"
  version "0.3.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cognitive3d"

  on_macos do
    on_intel do
      url "https://github.com/CognitiveVR/cognitive3d-releases/releases/download/v#{version}/cognitive3d_#{version}_Darwin_x86_64.tar.gz"
      sha256 "08b01973c7ecba1da353346e0e4ba995d1f91c35ac82a53baaaaf061c711dad4"
    end
    on_arm do
      url "https://github.com/CognitiveVR/cognitive3d-releases/releases/download/v#{version}/cognitive3d_#{version}_Darwin_arm64.tar.gz"
      sha256 "1bcae63991c90be686b0f7fbc9aa3240b012cdb74d7bcbc89617455c89388ec7"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/CognitiveVR/cognitive3d-releases/releases/download/v#{version}/cognitive3d_#{version}_Linux_x86_64.tar.gz"
      sha256 "fd2457eb2d0ef39459aafd414d20affc5cfa3fe121a3b566d6cd6d9b80f78db7"
    end
    on_arm do
      url "https://github.com/CognitiveVR/cognitive3d-releases/releases/download/v#{version}/cognitive3d_#{version}_Linux_arm64.tar.gz"
      sha256 "0c2323540ef1ab6d0d3511875f128961de43279d83aeadd44114ea15d55f2e2f"
    end
  end

  # No zap stanza required
end
